// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

var TableNames = struct {
	Agencies          string
	Blobs             string
	IssueTokens       string
	Managers          string
	Notifications     string
	PasswordHashes    string
	Privacies         string
	Properties        string
	PropertyBlobs     string
	ResetPasswords    string
	SchemaMigrations  string
	UserNotifications string
	UserPrivacies     string
	Users             string
}{
	Agencies:          "agencies",
	Blobs:             "blobs",
	IssueTokens:       "issue_tokens",
	Managers:          "managers",
	Notifications:     "notifications",
	PasswordHashes:    "password_hashes",
	Privacies:         "privacies",
	Properties:        "properties",
	PropertyBlobs:     "property_blobs",
	ResetPasswords:    "reset_passwords",
	SchemaMigrations:  "schema_migrations",
	UserNotifications: "user_notifications",
	UserPrivacies:     "user_privacies",
	Users:             "users",
}
