// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// PasswordHash is an object representing the database table.
type PasswordHash struct {
	UserID       string    `boiler:"user_id" boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	PasswordHash string    `boiler:"password_hash" boil:"password_hash" json:"password_hash" toml:"password_hash" yaml:"password_hash"`
	UpdatedAt    time.Time `boiler:"updated_at" boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	CreatedAt    time.Time `boiler:"created_at" boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	DeletedAt    null.Time `boiler:"deleted_at" boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *passwordHashR `boiler:"-" boil:"-" json:"-" toml:"-" yaml:"-"`
	L passwordHashL  `boiler:"-" boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PasswordHashColumns = struct {
	UserID       string
	PasswordHash string
	UpdatedAt    string
	CreatedAt    string
	DeletedAt    string
}{
	UserID:       "user_id",
	PasswordHash: "password_hash",
	UpdatedAt:    "updated_at",
	CreatedAt:    "created_at",
	DeletedAt:    "deleted_at",
}

var PasswordHashTableColumns = struct {
	UserID       string
	PasswordHash string
	UpdatedAt    string
	CreatedAt    string
	DeletedAt    string
}{
	UserID:       "password_hashes.user_id",
	PasswordHash: "password_hashes.password_hash",
	UpdatedAt:    "password_hashes.updated_at",
	CreatedAt:    "password_hashes.created_at",
	DeletedAt:    "password_hashes.deleted_at",
}

// Generated where

var PasswordHashWhere = struct {
	UserID       whereHelperstring
	PasswordHash whereHelperstring
	UpdatedAt    whereHelpertime_Time
	CreatedAt    whereHelpertime_Time
	DeletedAt    whereHelpernull_Time
}{
	UserID:       whereHelperstring{field: "\"password_hashes\".\"user_id\""},
	PasswordHash: whereHelperstring{field: "\"password_hashes\".\"password_hash\""},
	UpdatedAt:    whereHelpertime_Time{field: "\"password_hashes\".\"updated_at\""},
	CreatedAt:    whereHelpertime_Time{field: "\"password_hashes\".\"created_at\""},
	DeletedAt:    whereHelpernull_Time{field: "\"password_hashes\".\"deleted_at\""},
}

// PasswordHashRels is where relationship names are stored.
var PasswordHashRels = struct {
	User string
}{
	User: "User",
}

// passwordHashR is where relationships are stored.
type passwordHashR struct {
	User *User `boiler:"User" boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*passwordHashR) NewStruct() *passwordHashR {
	return &passwordHashR{}
}

func (r *passwordHashR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

// passwordHashL is where Load methods for each relationship are stored.
type passwordHashL struct{}

var (
	passwordHashAllColumns            = []string{"user_id", "password_hash", "updated_at", "created_at", "deleted_at"}
	passwordHashColumnsWithoutDefault = []string{"user_id", "password_hash"}
	passwordHashColumnsWithDefault    = []string{"updated_at", "created_at", "deleted_at"}
	passwordHashPrimaryKeyColumns     = []string{"user_id"}
	passwordHashGeneratedColumns      = []string{}
)

type (
	// PasswordHashSlice is an alias for a slice of pointers to PasswordHash.
	// This should almost always be used instead of []PasswordHash.
	PasswordHashSlice []*PasswordHash
	// PasswordHashHook is the signature for custom PasswordHash hook methods
	PasswordHashHook func(boil.Executor, *PasswordHash) error

	passwordHashQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	passwordHashType                 = reflect.TypeOf(&PasswordHash{})
	passwordHashMapping              = queries.MakeStructMapping(passwordHashType)
	passwordHashPrimaryKeyMapping, _ = queries.BindMapping(passwordHashType, passwordHashMapping, passwordHashPrimaryKeyColumns)
	passwordHashInsertCacheMut       sync.RWMutex
	passwordHashInsertCache          = make(map[string]insertCache)
	passwordHashUpdateCacheMut       sync.RWMutex
	passwordHashUpdateCache          = make(map[string]updateCache)
	passwordHashUpsertCacheMut       sync.RWMutex
	passwordHashUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var passwordHashAfterSelectHooks []PasswordHashHook

var passwordHashBeforeInsertHooks []PasswordHashHook
var passwordHashAfterInsertHooks []PasswordHashHook

var passwordHashBeforeUpdateHooks []PasswordHashHook
var passwordHashAfterUpdateHooks []PasswordHashHook

var passwordHashBeforeDeleteHooks []PasswordHashHook
var passwordHashAfterDeleteHooks []PasswordHashHook

var passwordHashBeforeUpsertHooks []PasswordHashHook
var passwordHashAfterUpsertHooks []PasswordHashHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PasswordHash) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range passwordHashAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PasswordHash) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range passwordHashBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PasswordHash) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range passwordHashAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PasswordHash) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range passwordHashBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PasswordHash) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range passwordHashAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PasswordHash) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range passwordHashBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PasswordHash) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range passwordHashAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PasswordHash) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range passwordHashBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PasswordHash) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range passwordHashAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPasswordHashHook registers your hook function for all future operations.
func AddPasswordHashHook(hookPoint boil.HookPoint, passwordHashHook PasswordHashHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		passwordHashAfterSelectHooks = append(passwordHashAfterSelectHooks, passwordHashHook)
	case boil.BeforeInsertHook:
		passwordHashBeforeInsertHooks = append(passwordHashBeforeInsertHooks, passwordHashHook)
	case boil.AfterInsertHook:
		passwordHashAfterInsertHooks = append(passwordHashAfterInsertHooks, passwordHashHook)
	case boil.BeforeUpdateHook:
		passwordHashBeforeUpdateHooks = append(passwordHashBeforeUpdateHooks, passwordHashHook)
	case boil.AfterUpdateHook:
		passwordHashAfterUpdateHooks = append(passwordHashAfterUpdateHooks, passwordHashHook)
	case boil.BeforeDeleteHook:
		passwordHashBeforeDeleteHooks = append(passwordHashBeforeDeleteHooks, passwordHashHook)
	case boil.AfterDeleteHook:
		passwordHashAfterDeleteHooks = append(passwordHashAfterDeleteHooks, passwordHashHook)
	case boil.BeforeUpsertHook:
		passwordHashBeforeUpsertHooks = append(passwordHashBeforeUpsertHooks, passwordHashHook)
	case boil.AfterUpsertHook:
		passwordHashAfterUpsertHooks = append(passwordHashAfterUpsertHooks, passwordHashHook)
	}
}

// One returns a single passwordHash record from the query.
func (q passwordHashQuery) One(exec boil.Executor) (*PasswordHash, error) {
	o := &PasswordHash{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler: failed to execute a one query for password_hashes")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PasswordHash records from the query.
func (q passwordHashQuery) All(exec boil.Executor) (PasswordHashSlice, error) {
	var o []*PasswordHash

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "boiler: failed to assign all query results to PasswordHash slice")
	}

	if len(passwordHashAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PasswordHash records in the query.
func (q passwordHashQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to count password_hashes rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q passwordHashQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "boiler: failed to check if password_hashes exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *PasswordHash) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (passwordHashL) LoadUser(e boil.Executor, singular bool, maybePasswordHash interface{}, mods queries.Applicator) error {
	var slice []*PasswordHash
	var object *PasswordHash

	if singular {
		var ok bool
		object, ok = maybePasswordHash.(*PasswordHash)
		if !ok {
			object = new(PasswordHash)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePasswordHash)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePasswordHash))
			}
		}
	} else {
		s, ok := maybePasswordHash.(*[]*PasswordHash)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePasswordHash)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePasswordHash))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &passwordHashR{}
		}
		args = append(args, object.UserID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &passwordHashR{}
			}

			for _, a := range args {
				if a == obj.UserID {
					continue Outer
				}
			}

			args = append(args, obj.UserID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, args...),
		qmhelper.WhereIsNull(`users.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.PasswordHash = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.PasswordHash = local
				break
			}
		}
	}

	return nil
}

// SetUser of the passwordHash to the related item.
// Sets o.R.User to related.
// Adds o to related.R.PasswordHash.
func (o *PasswordHash) SetUser(exec boil.Executor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"password_hashes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, passwordHashPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.UserID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &passwordHashR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			PasswordHash: o,
		}
	} else {
		related.R.PasswordHash = o
	}

	return nil
}

// PasswordHashes retrieves all the records using an executor.
func PasswordHashes(mods ...qm.QueryMod) passwordHashQuery {
	mods = append(mods, qm.From("\"password_hashes\""), qmhelper.WhereIsNull("\"password_hashes\".\"deleted_at\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"password_hashes\".*"})
	}

	return passwordHashQuery{q}
}

// FindPasswordHash retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPasswordHash(exec boil.Executor, userID string, selectCols ...string) (*PasswordHash, error) {
	passwordHashObj := &PasswordHash{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"password_hashes\" where \"user_id\"=$1 and \"deleted_at\" is null", sel,
	)

	q := queries.Raw(query, userID)

	err := q.Bind(nil, exec, passwordHashObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler: unable to select from password_hashes")
	}

	if err = passwordHashObj.doAfterSelectHooks(exec); err != nil {
		return passwordHashObj, err
	}

	return passwordHashObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PasswordHash) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("boiler: no password_hashes provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}
	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(passwordHashColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	passwordHashInsertCacheMut.RLock()
	cache, cached := passwordHashInsertCache[key]
	passwordHashInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			passwordHashAllColumns,
			passwordHashColumnsWithDefault,
			passwordHashColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(passwordHashType, passwordHashMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(passwordHashType, passwordHashMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"password_hashes\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"password_hashes\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "boiler: unable to insert into password_hashes")
	}

	if !cached {
		passwordHashInsertCacheMut.Lock()
		passwordHashInsertCache[key] = cache
		passwordHashInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// Update uses an executor to update the PasswordHash.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PasswordHash) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	passwordHashUpdateCacheMut.RLock()
	cache, cached := passwordHashUpdateCache[key]
	passwordHashUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			passwordHashAllColumns,
			passwordHashPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("boiler: unable to update password_hashes, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"password_hashes\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, passwordHashPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(passwordHashType, passwordHashMapping, append(wl, passwordHashPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update password_hashes row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by update for password_hashes")
	}

	if !cached {
		passwordHashUpdateCacheMut.Lock()
		passwordHashUpdateCache[key] = cache
		passwordHashUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(exec)
}

// UpdateAll updates all rows with the specified column values.
func (q passwordHashQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update all for password_hashes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to retrieve rows affected for password_hashes")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PasswordHashSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("boiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), passwordHashPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"password_hashes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, passwordHashPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update all in passwordHash slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to retrieve rows affected all in update all passwordHash")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PasswordHash) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("boiler: no password_hashes provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime
	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(passwordHashColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	passwordHashUpsertCacheMut.RLock()
	cache, cached := passwordHashUpsertCache[key]
	passwordHashUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			passwordHashAllColumns,
			passwordHashColumnsWithDefault,
			passwordHashColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			passwordHashAllColumns,
			passwordHashPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("boiler: unable to upsert password_hashes, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(passwordHashPrimaryKeyColumns))
			copy(conflict, passwordHashPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"password_hashes\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(passwordHashType, passwordHashMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(passwordHashType, passwordHashMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "boiler: unable to upsert password_hashes")
	}

	if !cached {
		passwordHashUpsertCacheMut.Lock()
		passwordHashUpsertCache[key] = cache
		passwordHashUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// Delete deletes a single PasswordHash record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PasswordHash) Delete(exec boil.Executor, hardDelete bool) (int64, error) {
	if o == nil {
		return 0, errors.New("boiler: no PasswordHash provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return 0, err
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), passwordHashPrimaryKeyMapping)
		sql = "DELETE FROM \"password_hashes\" WHERE \"user_id\"=$1"
	} else {
		currTime := time.Now().In(boil.GetLocation())
		o.DeletedAt = null.TimeFrom(currTime)
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"password_hashes\" SET %s WHERE \"user_id\"=$2",
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		valueMapping, err := queries.BindMapping(passwordHashType, passwordHashMapping, append(wl, passwordHashPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), valueMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete from password_hashes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by delete for password_hashes")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q passwordHashQuery) DeleteAll(exec boil.Executor, hardDelete bool) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("boiler: no passwordHashQuery provided for delete all")
	}

	if hardDelete {
		queries.SetDelete(q.Query)
	} else {
		currTime := time.Now().In(boil.GetLocation())
		queries.SetUpdate(q.Query, M{"deleted_at": currTime})
	}

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete all from password_hashes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by deleteall for password_hashes")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PasswordHashSlice) DeleteAll(exec boil.Executor, hardDelete bool) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(passwordHashBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), passwordHashPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
		}
		sql = "DELETE FROM \"password_hashes\" WHERE " +
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, passwordHashPrimaryKeyColumns, len(o))
	} else {
		currTime := time.Now().In(boil.GetLocation())
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), passwordHashPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
			obj.DeletedAt = null.TimeFrom(currTime)
		}
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"password_hashes\" SET %s WHERE "+
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 2, passwordHashPrimaryKeyColumns, len(o)),
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		args = append([]interface{}{currTime}, args...)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete all from passwordHash slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by deleteall for password_hashes")
	}

	if len(passwordHashAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PasswordHash) Reload(exec boil.Executor) error {
	ret, err := FindPasswordHash(exec, o.UserID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PasswordHashSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PasswordHashSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), passwordHashPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"password_hashes\".* FROM \"password_hashes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, passwordHashPrimaryKeyColumns, len(*o)) +
		"and \"deleted_at\" is null"

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to reload all in PasswordHashSlice")
	}

	*o = slice

	return nil
}

// PasswordHashExists checks if the PasswordHash row exists.
func PasswordHashExists(exec boil.Executor, userID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"password_hashes\" where \"user_id\"=$1 and \"deleted_at\" is null limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, userID)
	}
	row := exec.QueryRow(sql, userID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "boiler: unable to check if password_hashes exists")
	}

	return exists, nil
}

// Exists checks if the PasswordHash row exists.
func (o *PasswordHash) Exists(exec boil.Executor) (bool, error) {
	return PasswordHashExists(exec, o.UserID)
}
